Update cicd-pipeline.yml
Improved error handling

diff --git a/.github/workflows/cicd-pipeline.yml b/.github/workflows/cicd-pipeline.yml
--- a/.github/workflows/cicd-pipeline.yml
+++ b/.github/workflows/cicd-pipeline.yml
@@ -21,25 +21,24 @@ jobs:
           echo "+++++++++++++++"
           
           cd ~/AI-Training-Consumer/
-          git pull || echo "❌ Error: git pull failed ❌"
+          git pull || { echo -e " ++++++++++++++++++++++++\n❌ Error pulling changes! ❌ \n ++++++++++++++++++++++++"; exit 1; }
           
           echo "+++++++++++++++"
           echo "🏗️ Building consumer-backend image......."
           echo "+++++++++++++++"
           
           cd ~/AI-Training-Consumer/consumer_backend
-          docker build -t consumer-backend:latest
-
+          docker build -t consumer-backend:latest || { echo -e " ++++++++++++++++++++++++++++++++++++++++++++++++\n❌ Error building consumer-backend image! ❌ \n ++++++++++++++++++++++++++++++++++++++++++++++++"; exit 1; }
           echo "+++++++++++++++"
           echo "🏗️ Building consumer-frontend image......."
           echo "+++++++++++++++"
           cd ~/AI-Training-Consumer/consumder_frontend
-          docker build -t consumer-frontend:latest
+          docker build -t consumer-frontend:latest || { echo -e " ++++++++++++++++++++++++\n❌ Error building consumer-frontend image! ❌ \n ++++++++++++++++++++++++"; exit 1; }
 
           echo "+++++++++++++++"
           echo "🏗️ Composing docker setup......."
           echo "+++++++++++++++"
           
           cd ~/AI-Training-Consumer/
-          docker compose down || echo "❌ Error: docker compose down failed ❌"
-          docker compose up -d || echo "❌ Error: docker compose up failed ❌"
+          docker compose down || { echo -e " ++++++++++++++++++++++++\n❌ Error composing down! ❌ \n ++++++++++++++++++++++++"; exit 1; }
+          docker compose up -d || { echo -e " ++++++++++++++++++++++++\n❌ Error composing up! ❌ \n ++++++++++++++++++++++++"; exit 1; }
